version: "3.7"
services:
  proyectos-micros:
    container_name: proyectos-micros
    image: proyectos-micros:v1
    build: 
      context: .
    ports:
      - "4002"
    networks:
      - proyectos-app

  proyectos-micros-2:
    container_name: proyectos-micros-2
    image: proyectos-micros:v1
    ports:
      - "4002"
    networks:
      - proyectos-app

  loader-balancer:
    container_name: loader-balancer
    image: loader-balancer:v1
    build: 
      context: ./loader-balancer
    ports:
      - "4003:80"
    networks:
      - proyectos-app
    enviroments:
      - MONGO_URI='mongodb+srv://admin:5KuozYQlmFeBz1nd@cluster0.fht34da.mongodb.net/'
      - PORT=4002
    
networks:
  proyectos-app: 
